services:

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: requirements/frontend/Dockerfile
#    ports:
#      - "5173:5173"  # Vite preview
    volumes:
      - ./tools/frontend:/app
    depends_on:
      - backend
    networks:
      - pongnet

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: requirements/backend/Dockerfile
#    ports:
#      - "3000:3000"
#      - "8080:8080"
    volumes:
      - ./tools/backend:/app
    networks:
      - pongnet

  nginx:
    container_name: nginx
    image: nginx
    build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
    ports:
        - "8080:80"
        - "4443:443"
    restart: always
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/ssl:/etc/nginx/ssl
      - ./srcs/tools:/tools
    networks:
        - pongnet
    depends_on:
        - frontend
        - backend

networks:
    pongnet:
        driver: bridge
  